# Generated by Django 2.2 on 2021-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未指定标题', help_text='考试标题', max_length=200)),
                ('description', models.TextField(blank=True, default='无描述', help_text='考试描述')),
                ('time', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
