# Generated by Django 2.2 on 2021-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostPost',
        ),
    ]
