# Generated by Django 2.2 on 2021-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0002_auto_20210220_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPost',
            new_name='Post',
        ),
    ]
