# Generated by Django 2.2 on 2021-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0003_auto_20210220_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=200)),
                ('content', models.TextField(help_text='内容')),
            ],
        ),
    ]
