# Generated by Django 2.2 on 2021-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0003_auto_20210221_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='value_Q1',
            field=models.IntegerField(default=0, help_text='Q1 Scores'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='value_Q2',
            field=models.IntegerField(default=75, help_text='Q2 Scores'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='value_Q3',
            field=models.IntegerField(default=150, help_text='Q3 Scores'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='value_max',
            field=models.IntegerField(default=150, help_text='Max Scores'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='value_min',
            field=models.IntegerField(default=0, help_text='Min Scores'),
        ),
    ]
