# Generated by Django 2.2 on 2021-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0004_auto_20210221_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='无名氏', help_text='学生姓名', max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('N', '保密')], help_text='性别', max_length=1, verbose_name='性别')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.IntegerField(choices=[(1, '高一'), (2, '高二'), (3, '高三')], default=1, help_text='请填入1或2或3，表示高一或高二或高三。', verbose_name='考试年级'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, default='暂无描述', help_text='考试描述', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(default='未指定标题', help_text='考试标题', max_length=200, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(default='', to='Exam_Info.Student'),
        ),
    ]
