# Generated by Django 2.2 on 2021-02-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0004_postexam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostExam',
            new_name='PostCat',
        ),
    ]
