# Generated by Django 3.1.7 on 2021-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0005_auto_20210221_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.IntegerField(choices=[(1, '高一'), (2, '高二'), (3, '高三')], default=1, help_text='选择年级', verbose_name='考试年级'),
        ),
    ]
