# Generated by Django 2.2 on 2021-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0005_auto_20210220_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcat',
            name='time',
            field=models.DateField(default='19491001'),
        ),
    ]
