# Generated by Django 2.2 on 2021-02-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0006_postcat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcat',
            name='time',
        ),
    ]
