# Generated by Django 2.2.19 on 2021-02-23 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0006_auto_20210221_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enter_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入学时间'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='考试时间'),
        ),
    ]
