# Generated by Django 2.2 on 2021-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0006_postcat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcat',
            name='time',
            field=models.DateField(default='1949-10-01'),
        ),
    ]
