# Generated by Django 2.2 on 2021-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0007_remove_postcat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcat',
            name='time',
            field=models.DateField(default='1994-10-01'),
        ),
    ]
