# Generated by Django 2.2.19 on 2021-02-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0008_auto_20210223_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yw', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='语文成绩')),
                ('sx', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数学成绩')),
                ('yy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='英语成绩')),
                ('wl', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='物理成绩')),
                ('hx', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='化学成绩')),
                ('sw', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='生物成绩')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='总分')),
                ('grade_rank', models.IntegerField()),
                ('class_rank', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Info.Exam', verbose_name='对应考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Info.Student', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
    ]
