# Generated by Django 2.2.19 on 2021-02-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0010_auto_20210224_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='value_Q1',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='value_Q2',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='value_Q3',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='value_max',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='value_min',
        ),
    ]
