# Generated by Django 2.2.19 on 2021-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0011_auto_20210224_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.IntegerField(help_text='数字即可', max_length=100, verbose_name='班级名称'),
        ),
    ]
