# Generated by Django 2.2.19 on 2021-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0012_auto_20210225_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.IntegerField(help_text='数字即可', verbose_name='班级名称'),
        ),
    ]
