# Generated by Django 2.2.19 on 2021-02-25 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0013_auto_20210225_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examscore',
            name='exam',
        ),
        migrations.AddField(
            model_name='examscore',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='exam_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='考试时间'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='exam_title',
            field=models.CharField(default='未知考试', max_length=200, verbose_name='考试标题'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
