# Generated by Django 2.2.19 on 2021-03-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0014_auto_20210225_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examscore',
            old_name='exam_date',
            new_name='time',
        ),
    ]
