# Generated by Django 2.2.19 on 2021-03-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0014_auto_20210307_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '考试', 'verbose_name_plural': '考试'},
        ),
        migrations.AlterField(
            model_name='examscore',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Info.Exam', verbose_name='考试'),
        ),
    ]
