# Generated by Django 2.2.19 on 2021-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Info', '0015_auto_20210306_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='exam_id',
            field=models.IntegerField(null=True, verbose_name='考试编号'),
        ),
    ]
